package view;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ControleFinanceiro;


/**
 *
 * @author rafae
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private ControleFinanceiro controle;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(ControleFinanceiro controle) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblMenu = new javax.swing.JLabel();
        JBtnAddDespesa = new javax.swing.JButton();
        JbtnAddReceita = new javax.swing.JButton();
        JBtnConsultarSaldo = new javax.swing.JButton();
        JBtnListarLancamentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblMenu.setText("MENU");

        JBtnAddDespesa.setText("Incluir Despesa");
        JBtnAddDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAddDespesaActionPerformed(evt);
            }
        });

        JbtnAddReceita.setText("Incluir Receita");
        JbtnAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAddReceitaActionPerformed(evt);
            }
        });

        JBtnConsultarSaldo.setText("Consultar Saldo");
        JBtnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoActionPerformed(evt);
            }
        });

        JBtnListarLancamentos.setText("Listar Lançamentos");
        JBtnListarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarLancamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JbtnAddReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnListarLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnAddDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(JLblMenu)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JLblMenu)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnAddDespesa)
                    .addComponent(JbtnAddReceita))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnConsultarSaldo)
                    .addComponent(JBtnListarLancamentos))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAddReceitaActionPerformed
        TelaCadastroReceita telaReceita = null;
        try {
            telaReceita = new TelaCadastroReceita(controle);
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaReceita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbtnAddReceitaActionPerformed

    private void JBtnAddDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAddDespesaActionPerformed
        TelaCadastroDespesa telaDespesa = new TelaCadastroDespesa(controle);
        telaDespesa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnAddDespesaActionPerformed

    private void JBtnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoActionPerformed
        TelaConsultaSaldo telaSaldo = new TelaConsultaSaldo(controle);
        telaSaldo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnConsultarSaldoActionPerformed

    private void JBtnListarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarLancamentosActionPerformed
        TelaListagem telaListagem = new TelaListagem(controle);
        telaListagem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnListarLancamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ControleFinanceiro controle = new ControleFinanceiro();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(controle).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAddDespesa;
    private javax.swing.JButton JBtnConsultarSaldo;
    private javax.swing.JButton JBtnListarLancamentos;
    private javax.swing.JLabel JLblMenu;
    private javax.swing.JButton JbtnAddReceita;
    // End of variables declaration//GEN-END:variables
}
