package view;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.ControleFinanceiro;
import model.Lancamento;

/**
 *
 * @author rafae
 */
public class TelaListagem extends javax.swing.JFrame {

    private ControleFinanceiro controle;

    /**
     * Creates new form TelaListagem
     */
    public TelaListagem(ControleFinanceiro controle) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblListagem = new javax.swing.JLabel();
        JBtnListarReceitas = new javax.swing.JButton();
        JBtnListarDespesas = new javax.swing.JButton();
        JBtnListagemCompleta = new javax.swing.JButton();
        jBtnListagemVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblListagem.setText("LISTAGEM");

        JBtnListarReceitas.setText("Listar Receitas");
        JBtnListarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarReceitasActionPerformed(evt);
            }
        });

        JBtnListarDespesas.setText("Listar Despesas");
        JBtnListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarDespesasActionPerformed(evt);
            }
        });

        JBtnListagemCompleta.setText("Listagem Completa");
        JBtnListagemCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListagemCompletaActionPerformed(evt);
            }
        });

        jBtnListagemVoltar.setText("Voltar");
        jBtnListagemVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListagemVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnListarReceitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JLblListagem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JBtnListarDespesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnListagemCompleta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jBtnListagemVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JLblListagem)
                .addGap(52, 52, 52)
                .addComponent(JBtnListarReceitas)
                .addGap(18, 18, 18)
                .addComponent(JBtnListarDespesas)
                .addGap(12, 12, 12)
                .addComponent(JBtnListagemCompleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBtnListagemVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnListagemVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListagemVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal(controle);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnListagemVoltarActionPerformed

    private void JBtnListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarDespesasActionPerformed
                                               
        List<Lancamento> despesas = controle.listarDespesas();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (Lancamento d : despesas) {
            area.append(d.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scroll, "Despesas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListarDespesasActionPerformed

    private void JBtnListarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarReceitasActionPerformed
       
        List<Lancamento> receitas = controle.listarReceitas();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (Lancamento r : receitas) {
            area.append(r.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scroll, "Receitas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListarReceitasActionPerformed

    private void JBtnListagemCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListagemCompletaActionPerformed
        
        List<String> lancamentoCompleto = controle.listarLancamentosOrdenados();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (String lc : lancamentoCompleto) {
            area.append(lc.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scroll, "Receitas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListagemCompletaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnListagemCompleta;
    private javax.swing.JButton JBtnListarDespesas;
    private javax.swing.JButton JBtnListarReceitas;
    private javax.swing.JLabel JLblListagem;
    private javax.swing.JButton jBtnListagemVoltar;
    // End of variables declaration//GEN-END:variables
}
