package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import model.ControleFinanceiro;
import model.Despesa;
import model.Lancamento;

/**
 *
 * @author rafae
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    private String caminhoAtualCSV = "dados.csv"; // valor padrão

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(ControleFinanceiro controle) {
        this.controle = controle; // <- aqui no início!

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Selecione o arquivo CSV para carregar");

        int resultado = chooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            caminhoAtualCSV = chooser.getSelectedFile().getAbsolutePath();
            this.controle.carregarCSV(caminhoAtualCSV); // já tá garantido
        }

        initComponents();
        disporDados();
        setLocationRelativeTo(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                JFileChooser chooser = new JFileChooser();
                chooser.setDialogTitle("Onde deseja salvar o CSV?");
                chooser.setSelectedFile(new java.io.File("dados.csv"));

                int resultado = chooser.showSaveDialog(null);
                if (resultado == JFileChooser.APPROVE_OPTION) {
                    String caminhoSalvar = chooser.getSelectedFile().getAbsolutePath();
                    controle.salvarCSV(caminhoSalvar);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void disporDados() {
        mostrarSaudacao();
        atualizarHora();
        carregarDadosDashboard();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new javax.swing.JPanel();
        painelControle = new javax.swing.JPanel();
        JbtnAddReceita = new javax.swing.JButton();
        JBtnAddDespesa = new javax.swing.JButton();
        painelConsulta = new javax.swing.JPanel();
        JBtnListarLancamentos = new javax.swing.JButton();
        JBtnConsultarSaldo = new javax.swing.JButton();
        panelSaldoGeral = new javax.swing.JPanel();
        labelSaldoGeral = new javax.swing.JLabel();
        labelValorSaldoGeral = new javax.swing.JLabel();
        panelSaldoAtual = new javax.swing.JPanel();
        labelSaldoAtual = new javax.swing.JLabel();
        labelValorSaldoAtual = new javax.swing.JLabel();
        panelDespesa = new javax.swing.JPanel();
        labelDespesa = new javax.swing.JLabel();
        labelValorDespesa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelSaudacao = new javax.swing.JLabel();
        labelRelogio = new javax.swing.JLabel();
        panelReceita = new javax.swing.JPanel();
        labelReceita = new javax.swing.JLabel();
        labelValorReceita = new javax.swing.JLabel();
        Alunos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        setResizable(false);

        painelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        painelControle.setBorder(javax.swing.BorderFactory.createTitledBorder("Controle"));

        JbtnAddReceita.setText("Incluir Receita");
        JbtnAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAddReceitaActionPerformed(evt);
            }
        });

        JBtnAddDespesa.setText("Incluir Despesa");
        JBtnAddDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAddDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelControleLayout = new javax.swing.GroupLayout(painelControle);
        painelControle.setLayout(painelControleLayout);
        painelControleLayout.setHorizontalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnAddReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnAddDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelControleLayout.setVerticalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JbtnAddReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnAddDespesa)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        painelConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        JBtnListarLancamentos.setText("Listar Lançamentos");
        JBtnListarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarLancamentosActionPerformed(evt);
            }
        });

        JBtnConsultarSaldo.setText("Consultar Saldo");
        JBtnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsultaLayout = new javax.swing.GroupLayout(painelConsulta);
        painelConsulta.setLayout(painelConsultaLayout);
        painelConsultaLayout.setHorizontalGroup(
            painelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnListarLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelConsultaLayout.setVerticalGroup(
            painelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBtnListarLancamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnConsultarSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSaldoGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSaldoGeral.setPreferredSize(new java.awt.Dimension(260, 150));

        labelSaldoGeral.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelSaldoGeral.setText("Saldo Geral");

        labelValorSaldoGeral.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelValorSaldoGeral.setText("[valor saldo geral]");

        javax.swing.GroupLayout panelSaldoGeralLayout = new javax.swing.GroupLayout(panelSaldoGeral);
        panelSaldoGeral.setLayout(panelSaldoGeralLayout);
        panelSaldoGeralLayout.setHorizontalGroup(
            panelSaldoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaldoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaldoGeral)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(panelSaldoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSaldoGeralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorSaldoGeral)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelSaldoGeralLayout.setVerticalGroup(
            panelSaldoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaldoGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaldoGeral)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(panelSaldoGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSaldoGeralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorSaldoGeral)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelSaldoAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSaldoAtual.setPreferredSize(new java.awt.Dimension(260, 150));

        labelSaldoAtual.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelSaldoAtual.setText("Saldo Atual");

        labelValorSaldoAtual.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelValorSaldoAtual.setText("[valor saldo atual]");

        javax.swing.GroupLayout panelSaldoAtualLayout = new javax.swing.GroupLayout(panelSaldoAtual);
        panelSaldoAtual.setLayout(panelSaldoAtualLayout);
        panelSaldoAtualLayout.setHorizontalGroup(
            panelSaldoAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaldoAtualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaldoAtual)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(panelSaldoAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSaldoAtualLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorSaldoAtual)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelSaldoAtualLayout.setVerticalGroup(
            panelSaldoAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaldoAtualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaldoAtual)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(panelSaldoAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSaldoAtualLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorSaldoAtual)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelDespesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDespesa.setPreferredSize(new java.awt.Dimension(260, 150));

        labelDespesa.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelDespesa.setText("Despesas");

        labelValorDespesa.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelValorDespesa.setText("[valor despesas]");

        javax.swing.GroupLayout panelDespesaLayout = new javax.swing.GroupLayout(panelDespesa);
        panelDespesa.setLayout(panelDespesaLayout);
        panelDespesaLayout.setHorizontalGroup(
            panelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDespesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDespesaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorDespesa)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelDespesaLayout.setVerticalGroup(
            panelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDespesa)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(panelDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDespesaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorDespesa)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        labelSaudacao.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelSaudacao.setText("[saudação]");

        labelRelogio.setFont(new java.awt.Font("Helvetica Neue", 2, 12)); // NOI18N
        labelRelogio.setText("[relogio]");
        labelRelogio.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                labelRelogioComponentShown(evt);
            }
        });
        labelRelogio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelRelogioPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRelogio)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaudacao, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(labelRelogio))
                .addContainerGap())
        );

        panelReceita.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelReceita.setPreferredSize(new java.awt.Dimension(260, 150));

        labelReceita.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        labelReceita.setText("Receitas");

        labelValorReceita.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        labelValorReceita.setText("[valor receitas]");

        javax.swing.GroupLayout panelReceitaLayout = new javax.swing.GroupLayout(panelReceita);
        panelReceita.setLayout(panelReceitaLayout);
        panelReceitaLayout.setHorizontalGroup(
            panelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReceita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelReceitaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorReceita)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelReceitaLayout.setVerticalGroup(
            panelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReceita)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(panelReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelReceitaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(labelValorReceita)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Alunos.setFont(new java.awt.Font("Helvetica Neue", 2, 12)); // NOI18N
        Alunos.setText("Rafael, Thomas e Raquel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSaldoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(Alunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSaldoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Alunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarSaudacao() {

        LocalTime horaAtual = LocalTime.now();

        if (horaAtual.isAfter(LocalTime.MIDNIGHT) && horaAtual.isBefore(LocalTime.NOON)) {
            this.labelSaudacao.setText("Bom dia");
        } else if (horaAtual.isAfter(LocalTime.NOON) && horaAtual.isBefore(LocalTime.of(18, 00, 00))) {
            this.labelSaudacao.setText("Boa tarde");
        } else {
            this.labelSaudacao.setText("Boa noite");
        }

    }

    private void carregarDadosDashboard() {

        double saldoTotal = 0;
        double saldoAtual = 0;
        double totalReceitas = 0;
        double totalDespesas = 0;

        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

        if (this.controle != null) {
            saldoTotal = controle.calcularSaldoTotal();
            saldoAtual = controle.calcularSaldoAteHoje(LocalDate.now());
            totalDespesas = controle.listarDespesas().stream()
                    .mapToDouble(Lancamento::getValor)
                    .sum();
            totalReceitas = controle.listarReceitas().stream()
                    .mapToDouble(Lancamento::getValor)
                    .sum();
        }

        labelValorSaldoGeral.setText(formatoMoeda.format(saldoTotal));
        labelValorSaldoAtual.setText(formatoMoeda.format(saldoAtual));
        labelValorReceita.setText(formatoMoeda.format(totalReceitas));
        labelValorDespesa.setText(formatoMoeda.format(totalDespesas));
    }

    public void salvarSePossivel() {
    if (caminhoAtualCSV != null && !caminhoAtualCSV.isEmpty()) {
        controle.salvarCSV(caminhoAtualCSV);
    }
}



    private void JbtnAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAddReceitaActionPerformed
        TelaCadastroReceita telaReceita = new TelaCadastroReceita(controle, this);
        telaReceita.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_JbtnAddReceitaActionPerformed

    private void JBtnAddDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAddDespesaActionPerformed
        TelaCadastroDespesa telaDespesa = new TelaCadastroDespesa(controle, this);
        telaDespesa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBtnAddDespesaActionPerformed

    private void JBtnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoActionPerformed
        TelaConsultaSaldo telaSaldo = new TelaConsultaSaldo(controle, this);
        telaSaldo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBtnConsultarSaldoActionPerformed

    private void JBtnListarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarLancamentosActionPerformed
        TelaListagem telaListagem = new TelaListagem(controle, this);
        telaListagem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBtnListarLancamentosActionPerformed

    private void atualizarHora() {
        String horaAtual = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss", Locale.forLanguageTag("PT-BR")));
        labelRelogio.setText(horaAtual);
    }

    private void labelRelogioComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_labelRelogioComponentShown

    }//GEN-LAST:event_labelRelogioComponentShown

    private void labelRelogioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelRelogioPropertyChange
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                atualizarHora();
            }
        }).start();
    }//GEN-LAST:event_labelRelogioPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ControleFinanceiro controle = new ControleFinanceiro();
                new TelaPrincipal(controle).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alunos;
    private javax.swing.JButton JBtnAddDespesa;
    private javax.swing.JButton JBtnConsultarSaldo;
    private javax.swing.JButton JBtnListarLancamentos;
    private javax.swing.JButton JbtnAddReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDespesa;
    private javax.swing.JLabel labelReceita;
    private javax.swing.JLabel labelRelogio;
    private javax.swing.JLabel labelSaldoAtual;
    private javax.swing.JLabel labelSaldoGeral;
    private javax.swing.JLabel labelSaudacao;
    private javax.swing.JLabel labelValorDespesa;
    private javax.swing.JLabel labelValorReceita;
    private javax.swing.JLabel labelValorSaldoAtual;
    private javax.swing.JLabel labelValorSaldoGeral;
    private javax.swing.JPanel painelConsulta;
    private javax.swing.JPanel painelControle;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel panelDespesa;
    private javax.swing.JPanel panelReceita;
    private javax.swing.JPanel panelSaldoAtual;
    private javax.swing.JPanel panelSaldoGeral;
    // End of variables declaration//GEN-END:variables
}
