package view;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.ControleFinanceiro;
import model.Lancamento;

/**
 *
 * @author rafae
 */
public class TelaListagem extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    private TelaPrincipal telaPrincipal;
    /**
     * Creates new form TelaListagem
     */
    public TelaListagem(ControleFinanceiro controle, TelaPrincipal telaPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBtnListarReceitas = new javax.swing.JButton();
        JBtnListarDespesas = new javax.swing.JButton();
        JBtnListagemCompleta = new javax.swing.JButton();
        jBtnListagemVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem"));

        JBtnListarReceitas.setText("Listar Receitas");
        JBtnListarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarReceitasActionPerformed(evt);
            }
        });

        JBtnListarDespesas.setText("Listar Despesas");
        JBtnListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListarDespesasActionPerformed(evt);
            }
        });

        JBtnListagemCompleta.setText("Listagem Completa");
        JBtnListagemCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnListagemCompletaActionPerformed(evt);
            }
        });

        jBtnListagemVoltar.setText("Voltar");
        jBtnListagemVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListagemVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JBtnListarReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnListagemCompleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnListarDespesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBtnListagemVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JBtnListarReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnListarDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnListagemCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jBtnListagemVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnListagemVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListagemVoltarActionPerformed
        this.setVisible(false);
        telaPrincipal.setVisible(true);
        telaPrincipal.disporDados();
    }//GEN-LAST:event_jBtnListagemVoltarActionPerformed

    private void JBtnListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarDespesasActionPerformed
                                               
        List<Lancamento> despesas = controle.listarDespesas();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (Lancamento d : despesas) {
            area.append(d.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scroll, "Despesas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListarDespesasActionPerformed

    private void JBtnListarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListarReceitasActionPerformed
       
        List<Lancamento> receitas = controle.listarReceitas();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (Lancamento r : receitas) {
            area.append(r.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(400, 300));

        JOptionPane.showMessageDialog(this, scroll, "Receitas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListarReceitasActionPerformed

    private void JBtnListagemCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnListagemCompletaActionPerformed
        
        List<String> lancamentoCompleto = controle.listarLancamentosOrdenados();

        JTextArea area = new JTextArea();
        area.setEditable(false);
        for (String lc : lancamentoCompleto) {
            area.append(lc.toString() + "\n");
        }

        JScrollPane scroll = new JScrollPane(area);
        scroll.setPreferredSize(new Dimension(500, 300));

        JOptionPane.showMessageDialog(this, scroll, "Receitas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBtnListagemCompletaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnListagemCompleta;
    private javax.swing.JButton JBtnListarDespesas;
    private javax.swing.JButton JBtnListarReceitas;
    private javax.swing.JButton jBtnListagemVoltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
