package view;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.ControleFinanceiro;
/**
 *
 * @author rafae
 */
public class TelaConsultaSaldo extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    /**
     * Creates new form TelaConsultaSaldo
     */
    public TelaConsultaSaldo(ControleFinanceiro controle) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConsultaSaldo = new javax.swing.JPanel();
        JBtnConsultarSaldo = new javax.swing.JButton();
        JBtnConsultarSaldoGeral1 = new javax.swing.JButton();
        jBtnSaldoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelConsultaSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Saldo"));

        JBtnConsultarSaldo.setText("Consultar data atual");
        JBtnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoActionPerformed(evt);
            }
        });

        JBtnConsultarSaldoGeral1.setText("Consultar geral");
        JBtnConsultarSaldoGeral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoGeral1ActionPerformed(evt);
            }
        });

        jBtnSaldoVoltar.setText("Voltar");
        jBtnSaldoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaldoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultaSaldoLayout = new javax.swing.GroupLayout(panelConsultaSaldo);
        panelConsultaSaldo.setLayout(panelConsultaSaldoLayout);
        panelConsultaSaldoLayout.setHorizontalGroup(
            panelConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaSaldoLayout.createSequentialGroup()
                .addGroup(panelConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaSaldoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnConsultarSaldoGeral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelConsultaSaldoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jBtnSaldoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelConsultaSaldoLayout.setVerticalGroup(
            panelConsultaSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaSaldoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnConsultarSaldoGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBtnSaldoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConsultaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoActionPerformed
        double saldo = controle.calcularSaldoAteHoje(LocalDate.now());
        JOptionPane.showMessageDialog(this, String.format("Saldo até hoje (%s): R$ %.2f", LocalDate.now(), saldo));
    }//GEN-LAST:event_JBtnConsultarSaldoActionPerformed

    private void jBtnSaldoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaldoVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal(controle);
        telaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSaldoVoltarActionPerformed

    private void JBtnConsultarSaldoGeral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoGeral1ActionPerformed
        double saldo = controle.calcularSaldoTotal();
        JOptionPane.showMessageDialog(this, String.format("Saldo geral: R$ %.2f", saldo));
    }//GEN-LAST:event_JBtnConsultarSaldoGeral1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConsultarSaldo;
    private javax.swing.JButton JBtnConsultarSaldoGeral1;
    private javax.swing.JButton jBtnSaldoVoltar;
    private javax.swing.JPanel panelConsultaSaldo;
    // End of variables declaration//GEN-END:variables
}
