package view;

import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import java.text.ParseException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.CategoriaDespesa;
import model.ControleFinanceiro;
import model.Despesa;

/**
 *
 * @author rafae
 */
public class TelaCadastroDespesa extends javax.swing.JFrame {
    
    private ControleFinanceiro controle;
    private TelaPrincipal telaPrincipal;

    /**
     * Creates new form TelaCadastroDespesa
     */
    public TelaCadastroDespesa(ControleFinanceiro controle, TelaPrincipal telaPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
        this.telaPrincipal = telaPrincipal;
        
    try {
        MaskFormatter mf = new MaskFormatter("####-##-##");
        mf.setPlaceholderCharacter('_');  
        jFtxtDataDespesa.setFormatterFactory(
            new DefaultFormatterFactory(mf)
        );
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlblCategoriaDespesa = new javax.swing.JLabel();
        JlblDataDespesa = new javax.swing.JLabel();
        JlblValorDespesa = new javax.swing.JLabel();
        JCbCategoriaDespesa = new javax.swing.JComboBox<>();
        jFtxtDataDespesa = new javax.swing.JFormattedTextField();
        JTxtValorDespesa = new javax.swing.JTextField();
        JBtnConfirmarDespesa = new javax.swing.JButton();
        jBtnDespesaVoltar = new javax.swing.JButton();
        JlblIncluirReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JlblCategoriaDespesa.setText("Categoria");

        JlblDataDespesa.setText("Data");

        JlblValorDespesa.setText("Valor");

        JCbCategoriaDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacao", "Transporte", "Residencia", "Saude", "Educacao", "Entretenimento", "Outras despesas" }));
        JCbCategoriaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbCategoriaDespesaActionPerformed(evt);
            }
        });

        jFtxtDataDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtxtDataDespesaActionPerformed(evt);
            }
        });

        JBtnConfirmarDespesa.setText("Confirmar");
        JBtnConfirmarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConfirmarDespesaActionPerformed(evt);
            }
        });

        jBtnDespesaVoltar.setText("Voltar");
        jBtnDespesaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDespesaVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JlblCategoriaDespesa)
                    .addComponent(JlblDataDespesa)
                    .addComponent(JlblValorDespesa)
                    .addComponent(JCbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFtxtDataDespesa)
                    .addComponent(JTxtValorDespesa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(JBtnConfirmarDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDespesaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlblCategoriaDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JlblDataDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFtxtDataDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JlblValorDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnConfirmarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDespesaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JlblIncluirReceita.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JlblIncluirReceita.setText("Incluir Despesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlblIncluirReceita)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlblIncluirReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbCategoriaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbCategoriaDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCbCategoriaDespesaActionPerformed

    private void jBtnDespesaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDespesaVoltarActionPerformed
        this.setVisible(false);
        telaPrincipal.setVisible(true);
        telaPrincipal.disporDados();
    }//GEN-LAST:event_jBtnDespesaVoltarActionPerformed

    private void jFtxtDataDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtxtDataDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtxtDataDespesaActionPerformed

    private void JBtnConfirmarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConfirmarDespesaActionPerformed
        try {
            double valor = Double.parseDouble(JTxtValorDespesa.getText());
            LocalDate data = LocalDate.parse(jFtxtDataDespesa.getText());
            String selecionado = (String) JCbCategoriaDespesa.getSelectedItem();
            CategoriaDespesa categoria = parseCategoria(selecionado);

            Despesa despesa = new Despesa(valor, data, categoria);
            controle.adicionarLancamento(despesa);
            JOptionPane.showMessageDialog(this, "Despesa cadastrada com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar despesa: " + ex.getMessage());
        }
    }//GEN-LAST:event_JBtnConfirmarDespesaActionPerformed

    /**
     * @param args the command line arguments
     */

    private CategoriaDespesa parseCategoria(String selecionado) {
        switch (selecionado) {
            case "Alimentacao":
                return CategoriaDespesa.ALIMENTACAO;
            case "Transporte":
                return CategoriaDespesa.TRANSPORTE;
            case "Residencia":
                return CategoriaDespesa.RESIDENCIA;
            case "Saude":
                return CategoriaDespesa.SAUDE;
            case "Educacao":
                return CategoriaDespesa.EDUCACAO;
            case "Entretenimento":
                return CategoriaDespesa.ENTRETENIMENTO;
            case "Outras despesas":
                return CategoriaDespesa.OUTRAS;
            default:
                throw new IllegalArgumentException("Categoria desconhecida: " + selecionado);
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConfirmarDespesa;
    private javax.swing.JComboBox<String> JCbCategoriaDespesa;
    private javax.swing.JTextField JTxtValorDespesa;
    private javax.swing.JLabel JlblCategoriaDespesa;
    private javax.swing.JLabel JlblDataDespesa;
    private javax.swing.JLabel JlblIncluirReceita;
    private javax.swing.JLabel JlblValorDespesa;
    private javax.swing.JButton jBtnDespesaVoltar;
    private javax.swing.JFormattedTextField jFtxtDataDespesa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
