package view;

import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import java.text.ParseException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.CategoriaReceita;
import model.ControleFinanceiro;
import model.Receita;

/**
 *
 * @author rafae
 */
public class TelaCadastroReceita extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    private TelaPrincipal telaPrincipal;
    /**
     * Creates new form TelaCadastroReceita
     */
    public TelaCadastroReceita(ControleFinanceiro controle, TelaPrincipal telaPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
        this.telaPrincipal = telaPrincipal;
        
    try {
        MaskFormatter mf = new MaskFormatter("####-##-##");
        mf.setPlaceholderCharacter('_');  
        jFtxtDataReceita.setFormatterFactory(
            new DefaultFormatterFactory(mf)
        );
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlblIncluirReceita = new javax.swing.JLabel();
        panelIncluirReceita = new javax.swing.JPanel();
        labelCategoriaReceita = new javax.swing.JLabel();
        JCbCategoriaReceita = new javax.swing.JComboBox<>();
        labelDataReceita = new javax.swing.JLabel();
        jFtxtDataReceita = new javax.swing.JFormattedTextField();
        labelValorReceita = new javax.swing.JLabel();
        JtxtValorReceita = new javax.swing.JTextField();
        JBtnConfirmarReceita = new javax.swing.JButton();
        jBtnReceitaVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JlblIncluirReceita.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JlblIncluirReceita.setText("Incluir Receita");

        panelIncluirReceita.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCategoriaReceita.setText("Categoria");

        JCbCategoriaReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salario", "Decimo terceiro", "Ferias", "Outras receitas" }));
        JCbCategoriaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbCategoriaReceitaActionPerformed(evt);
            }
        });

        labelDataReceita.setText("Data");

        jFtxtDataReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtxtDataReceitaActionPerformed(evt);
            }
        });

        labelValorReceita.setText("Valor");

        JtxtValorReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtValorReceitaActionPerformed(evt);
            }
        });

        JBtnConfirmarReceita.setText("Confirmar");
        JBtnConfirmarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConfirmarReceitaActionPerformed(evt);
            }
        });

        jBtnReceitaVoltar.setText("Voltar");
        jBtnReceitaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceitaVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIncluirReceitaLayout = new javax.swing.GroupLayout(panelIncluirReceita);
        panelIncluirReceita.setLayout(panelIncluirReceitaLayout);
        panelIncluirReceitaLayout.setHorizontalGroup(
            panelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirReceitaLayout.createSequentialGroup()
                .addGroup(panelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIncluirReceitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JtxtValorReceita)
                            .addComponent(labelCategoriaReceita, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCbCategoriaReceita, javax.swing.GroupLayout.Alignment.LEADING, 0, 136, Short.MAX_VALUE)
                            .addComponent(labelDataReceita, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorReceita, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFtxtDataReceita, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(panelIncluirReceitaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(JBtnConfirmarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnReceitaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelIncluirReceitaLayout.setVerticalGroup(
            panelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncluirReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCategoriaReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCbCategoriaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDataReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFtxtDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelValorReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtxtValorReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnConfirmarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReceitaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlblIncluirReceita)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIncluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JlblIncluirReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIncluirReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbCategoriaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbCategoriaReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCbCategoriaReceitaActionPerformed

    private void jBtnReceitaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceitaVoltarActionPerformed
        this.setVisible(false);
        telaPrincipal.setVisible(true);
        telaPrincipal.disporDados();
    }//GEN-LAST:event_jBtnReceitaVoltarActionPerformed

    private void JtxtValorReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtValorReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtValorReceitaActionPerformed

    private void JBtnConfirmarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConfirmarReceitaActionPerformed
        try {
            double valor = Double.parseDouble(JtxtValorReceita.getText());
            LocalDate data = LocalDate.parse(jFtxtDataReceita.getText());
            String selecionado = (String) JCbCategoriaReceita.getSelectedItem();
            CategoriaReceita categoria = parseCategoria(selecionado);

            Receita receita = new Receita(valor, data, categoria);
            controle.adicionarLancamento(receita);
            JOptionPane.showMessageDialog(this, "Receita cadastrada com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar receita: " + ex.getMessage());
        }
    }//GEN-LAST:event_JBtnConfirmarReceitaActionPerformed

    private void jFtxtDataReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtxtDataReceitaActionPerformed

    }//GEN-LAST:event_jFtxtDataReceitaActionPerformed

    
    private CategoriaReceita parseCategoria(String selecionado) {
        switch (selecionado) {
            case "Salario":
                return CategoriaReceita.SALARIO;
            case "Decimo terceiro":
                return CategoriaReceita.DECIMO_TERCEIRO;
            case "Ferias":
                return CategoriaReceita.FERIAS;
            case "Outras receitas":
                return CategoriaReceita.OUTRAS;
            default:
                throw new IllegalArgumentException("Categoria desconhecida: " + selecionado);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConfirmarReceita;
    private javax.swing.JComboBox<String> JCbCategoriaReceita;
    private javax.swing.JLabel JlblIncluirReceita;
    private javax.swing.JTextField JtxtValorReceita;
    private javax.swing.JButton jBtnReceitaVoltar;
    private javax.swing.JFormattedTextField jFtxtDataReceita;
    private javax.swing.JLabel labelCategoriaReceita;
    private javax.swing.JLabel labelDataReceita;
    private javax.swing.JLabel labelValorReceita;
    private javax.swing.JPanel panelIncluirReceita;
    // End of variables declaration//GEN-END:variables
}
