package view;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.ControleFinanceiro;
/**
 *
 * @author rafae
 */
public class TelaConsultaSaldo extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    /**
     * Creates new form TelaConsultaSaldo
     */
    public TelaConsultaSaldo(ControleFinanceiro controle) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblConsultarSaldo = new javax.swing.JLabel();
        JBtnConsultarSaldo = new javax.swing.JButton();
        jBtnSaldoVoltar = new javax.swing.JButton();
        JBtnConsultarSaldoGeral1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLblConsultarSaldo.setText("CONSULTAR SALDO");

        JBtnConsultarSaldo.setText("Consultar data atual");
        JBtnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoActionPerformed(evt);
            }
        });

        jBtnSaldoVoltar.setText("Voltar");
        jBtnSaldoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaldoVoltarActionPerformed(evt);
            }
        });

        JBtnConsultarSaldoGeral1.setText("Consultar geral");
        JBtnConsultarSaldoGeral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarSaldoGeral1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(JLblConsultarSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jBtnSaldoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JBtnConsultarSaldoGeral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JLblConsultarSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(JBtnConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBtnConsultarSaldoGeral1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jBtnSaldoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoActionPerformed
        double saldo = controle.calcularSaldoAteHoje(LocalDate.now());
        JOptionPane.showMessageDialog(this, String.format("Saldo até hoje (%s): R$ %.2f", LocalDate.now(), saldo));
    }//GEN-LAST:event_JBtnConsultarSaldoActionPerformed

    private void jBtnSaldoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaldoVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal(controle);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSaldoVoltarActionPerformed

    private void JBtnConsultarSaldoGeral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarSaldoGeral1ActionPerformed
        double saldo = controle.calcularSaldoTotal();
        JOptionPane.showMessageDialog(this, String.format("Saldo geral: R$ %.2f", saldo));
    }//GEN-LAST:event_JBtnConsultarSaldoGeral1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConsultarSaldo;
    private javax.swing.JButton JBtnConsultarSaldoGeral1;
    private javax.swing.JLabel JLblConsultarSaldo;
    private javax.swing.JButton jBtnSaldoVoltar;
    // End of variables declaration//GEN-END:variables
}
