package view;

import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import java.text.ParseException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.CategoriaReceita;
import model.ControleFinanceiro;
import model.Receita;

/**
 *
 * @author rafae
 */
public class TelaCadastroReceita extends javax.swing.JFrame {

    private ControleFinanceiro controle;
    /**
     * Creates new form TelaCadastroReceita
     */
    public TelaCadastroReceita(ControleFinanceiro controle) {
        initComponents();
        setLocationRelativeTo(null);
        this.controle = controle;
        
    try {
        MaskFormatter mf = new MaskFormatter("####-##-##");
        mf.setPlaceholderCharacter('_');  
        jFtxtDataReceita.setFormatterFactory(
            new DefaultFormatterFactory(mf)
        );
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlblIncluirReceita = new javax.swing.JLabel();
        JlblValorReceita = new javax.swing.JLabel();
        JtxtValorReceita = new javax.swing.JTextField();
        JlblDataReceita = new javax.swing.JLabel();
        JlblCategoriaReceita = new javax.swing.JLabel();
        JCbCategoriaReceita = new javax.swing.JComboBox<>();
        jBtnReceitaVoltar = new javax.swing.JButton();
        JBtnConfirmarReceita1 = new javax.swing.JButton();
        jFtxtDataReceita = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlblIncluirReceita.setText("INCLUIR RECEITA");

        JlblValorReceita.setText("Valor");

        JtxtValorReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtValorReceitaActionPerformed(evt);
            }
        });

        JlblDataReceita.setText("Data");

        JlblCategoriaReceita.setText("Categoria");

        JCbCategoriaReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salario", "Decimo terceiro", "Ferias", "Outras receitas" }));
        JCbCategoriaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCbCategoriaReceitaActionPerformed(evt);
            }
        });

        jBtnReceitaVoltar.setText("Voltar");
        jBtnReceitaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceitaVoltarActionPerformed(evt);
            }
        });

        JBtnConfirmarReceita1.setText("Confirmar");
        JBtnConfirmarReceita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConfirmarReceita1ActionPerformed(evt);
            }
        });

        jFtxtDataReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtxtDataReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(JlblIncluirReceita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtnConfirmarReceita1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jBtnReceitaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtxtValorReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblValorReceita))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlblDataReceita)
                    .addComponent(jFtxtDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCbCategoriaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlblCategoriaReceita))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JlblIncluirReceita)
                        .addGap(69, 69, 69)
                        .addComponent(JlblCategoriaReceita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCbCategoriaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlblValorReceita, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JlblDataReceita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtxtValorReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFtxtDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReceitaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnConfirmarReceita1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCbCategoriaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCbCategoriaReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCbCategoriaReceitaActionPerformed

    private void jBtnReceitaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceitaVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal(controle);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnReceitaVoltarActionPerformed

    private void JtxtValorReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtValorReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtValorReceitaActionPerformed

    private void JBtnConfirmarReceita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConfirmarReceita1ActionPerformed
        try {
            double valor = Double.parseDouble(JtxtValorReceita.getText());
            LocalDate data = LocalDate.parse(jFtxtDataReceita.getText());
            String selecionado = (String) JCbCategoriaReceita.getSelectedItem();
            CategoriaReceita categoria = parseCategoria(selecionado);

            Receita receita = new Receita(valor, data, categoria);
            controle.adicionarLancamento(receita);
            JOptionPane.showMessageDialog(this, "Receita cadastrada com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar receita: " + ex.getMessage());
        }
    }//GEN-LAST:event_JBtnConfirmarReceita1ActionPerformed

    private void jFtxtDataReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtxtDataReceitaActionPerformed

    }//GEN-LAST:event_jFtxtDataReceitaActionPerformed

    
    private CategoriaReceita parseCategoria(String selecionado) {
        switch (selecionado) {
            case "Salario":
                return CategoriaReceita.SALARIO;
            case "Decimo terceiro":
                return CategoriaReceita.DECIMO_TERCEIRO;
            case "Ferias":
                return CategoriaReceita.FERIAS;
            case "Outras receitas":
                return CategoriaReceita.OUTRAS;
            default:
                throw new IllegalArgumentException("Categoria desconhecida: " + selecionado);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConfirmarReceita1;
    private javax.swing.JComboBox<String> JCbCategoriaReceita;
    private javax.swing.JLabel JlblCategoriaReceita;
    private javax.swing.JLabel JlblDataReceita;
    private javax.swing.JLabel JlblIncluirReceita;
    private javax.swing.JLabel JlblValorReceita;
    private javax.swing.JTextField JtxtValorReceita;
    private javax.swing.JButton jBtnReceitaVoltar;
    private javax.swing.JFormattedTextField jFtxtDataReceita;
    // End of variables declaration//GEN-END:variables
}
